# Generated by Django 4.1 on 2022-09-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup1', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup2', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('ingredient', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
