# Generated by Django 4.1 on 2022-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_linktoobtain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
